export const CODE = {
    RELIANCE: "RELIANCE.BSE",
    AIRTEL: "532454.BSE",
    HCL:"HCLTECH.BSE",
    INFOSYS:"INFY.BSE",
    TCS:"TCS.BSE",
    SBI:"SBIN.BSE",
    LT:"LT.BSE",
    TECHMAHINDRA:"532755.BSE",
    MICROSOFT:"MSFT",
    APPLE:"AAPL",
    AMAZON:"AMZN",
    ALPHABET:"GOOG",
    FACEBOOK:"FB",
    INTEL:"INTC",
    ADOBE:"ADBE",
    NETFLIX:"NFLX",
}

export const DESCRIPTION = {
    RELIANCE: "Reliance Industries is engaged in activities spanning across hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, retail, digital services and financial services.",
    TECHMAHINDRA: "Tech Mahindra Limited is an Indian multinational technology company, providing information technology and business process outsourcing services",
    LT:"L&T Infotech is a global IT services and solutions provider provide the winning edge to the clients by leveraging our Business-to-IT Connect and Deeply Committed People",
    HCL: "HCL Technologies is a next-generation global technology company that helps enterprises reimagine their businesses for the digital age technologies such as analytics, cloud, IoT, and automation HCL offers an integrated portfolio of products and services through their business units",
    INFOSYS:"Infosys LTD is a global technology service firm that defines, designs and delivers information technology(IT)-enables business solutions to their clients. The company provides end-to-end business solutions that leverage technology for their clients.",
    AIRTEL: "Airtel is the India's leading telecommunications company, airtel brand has played the role of a major catalyst in India's reforms, contributing to its economic resurgence.",
    TCS:"Tata COnsultancy Service Ltd is a leading global IT services, consulting and business solutions organization, The company offers a range of IT services,outsourcing business solutions The company is a part of Tata Group, one of India's most respected business conglomerates",
    SBI: "SBI is the 43rd largest bank in the world and ranked 236th in the Fortune Global 500 list of the world's biggest corporations of 2019. A nationalised bank, it is the largest in India with a 23% market share by assets and a 25% share of the total loan and deposits market",
    MICROSOFT: "Microsoft Corporation (MS) is an American multinational technology company. Its best-known software products are the Microsoft Windows line of operating systems, the Microsoft Office suite, and the Internet Explorer and Edge web browsers",
    APPLE:"Apple designs, manufactures and markets mobile communication and media devices, personal computers and portable digital music players. The Company sells a range of related software, services, accessories, networking solutions and third-party digital content and applications",
    AMAZON:"Amazon.com, Inc., is an American multinational technology company based in Seattle, Washington, which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.",
    ALPHABET:"Alphabet is mostly a collection of companies. The largest of which, of course, is Google.Alphabet is about businesses prospering through strong leaders and independence.",
    FACEBOOK:"Facebook operates as a social networking company worldwide. The company engages in the development of social media applications for people to connect through mobile devices, personal computers, and other surfaces.",
    INTEL:"Intel Corp. is one of the computer chip companies, Intel offers platform products that incorporate various components and technologies, including a microprocessor and chipset, a stand-alone SoC, or a multichip package",
    ADOBE:"Adobe Officially known as Adobe Systems, the company is known for its multimedia and creativity software products. Popular products include Photoshop, Acrobat Reader, and Adobe Creative Cloud",
    NETFLIX:"Netflix, in full Netflix, Inc., media-streaming and video-rental company founded in 1997 by American entrepreneurs Reed Hastings and Marc Randolph. It is also involved in the creation of original programming."
}